### ISSUE TITLE
Undefined behavior

### ISSUE THREAD

**Issue by SimonTechv** [ArteryTek/AT32F435_437_Firmware_Library#3]
Perhaps this is a typo? Why does this command require waiting for an interrupt?

https://github.com/ArteryTek/AT32F435_437_Firmware_Library/blob/25439cc6650a8ae0345934e8707a5f38c7ae41f8/project/at_start_f437/examples/sdio/sd_mmc_card/src/at32_sdio.c#L811

**Comment by ArteryTek** [comment]
Thanks for your reply, fixed in next version.

**Comment by SimonTechv** [comment]
There is little written in the documentation about wait for pending and wait for interrupt SDIO (RM AT32F437). Could you provide additional explanations, please?
